### ISSUE TITLE
Problem making it work

### ISSUE THREAD

**Issue by berta24** [ricardotx/qbittorrent_telegram_notification#6]
Does it work for you?
looks like my qbittorrent uses a total different syntax..
in declaring and using a variable my qbittorrent requires to use '${1}' instead of your ${1}.
with your code a msg is never sent and the log shows 
![image](https://github.com/rteixeirax/qbittorrent_telegram_notification/assets/25983005/aa07e185-6411-4842-a2b5-2f50610a05cb)
this is my qbit config
![image](https://github.com/rteixeirax/qbittorrent_telegram_notification/assets/25983005/ab8cf173-cba2-413f-b6eb-f15318c45a2a)

in the past i had it working with this script, with bot_token and chat_id explicitly written,

```
#!/bin/bash
curl -S -X POST 'https://api.telegram.org/bot***BOT_TOKEN***/sendMessagechat_id=***CHAT_ID***&text=DownloadIniziato'${1}'&parse_mode=HTML'

```
the problem was on the name, it would show only the first word if there was a space in between, like in the example above, 
Resident Evil Death Island 2023 Bluray 2160p AV1 HDR10 EN_FR_ES_ITA OPUS 7.1-UH was shorten to:
![image](https://github.com/rteixeirax/qbittorrent_telegram_notification/assets/25983005/e410adc1-c1cb-49f4-8a92-52aabdbc1a34)

**Comment by rteixeirax** [comment]
@berta24, did you create the new file [bot_credentials.sh](https://github.com/rteixeirax/qbittorrent_telegram_notification/blob/master/src/bot_credentials.sh) in the same folder as the `qbittorrent` script, with your telegram credentials?

**Comment by berta24** [comment]
> @berta24, did you create the new file [bot_credentials.sh](https://github.com/rteixeirax/qbittorrent_telegram_notification/blob/master/src/bot_credentials.sh) in the same folder as the `qbittorrent` script, with your telegram credentials?

![image](https://github.com/rteixeirax/qbittorrent_telegram_notification/assets/25983005/ef970c76-2eb2-4d96-8eec-45b1f84e5f5c)
yes same folder

**Comment by rteixeirax** [comment]
@berta24, it seems like the code had a bug fixed in this [PR](https://github.com/rteixeirax/qbittorrent_telegram_notification/pull/7). Can you confirm that the script is now working for you, as it should?

**Comment by berta24** [comment]
@rteixeirax, sorry for the late response... 
it's still not working, i've downloaded the fresh files, added both in the same folder and edited the credentials one, inserted into qbittorent, added a torrent but no message arrives...
in the log i see only this 
![image](https://github.com/rteixeirax/qbittorrent_telegram_notification/assets/25983005/22425c45-cb6d-4590-b69b-6b318f20c6b9)
right now i'm using this code and it seems to be working, maybe it can help
```
#!/bin/bash
TBT="BOT_TOKEN"
TCI="CHAT_ID"
#Function to send Telegram notification
send_telegram_notification(){
message="$1"
curl -s -X POST "https://api.telegram.org/bot${TBT}/sendMessage" \
-d "chat_id=$TCI" \
-d "text=$message" > /dev/null
echo "Telegram notification sent successfully."
}
#qBittorrent variables
name="$1"
#Customize the message as needed
message="Download Started: $name"
#Send Telegram notification
send_telegram_notification "$message"
```

**Comment by rteixeirax** [comment]
@shaneoreilly since you have made the changes for this new version of the script, could you please take a look at the @berta24 problem to check if the issue is related to the changes?

**Comment by rteixeirax** [comment]
Closed due to inactivity.
